apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  # --- Default values ---
  source:
    repoURL: https://github.com/s-riviere/kth-devops-tutorial.git
    targetRevision: HEAD
    path: gitops-argocd/gitops/app
  # --- Default values ---

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
